name: Selenoid Tests Workflow
on:
  push:
    branches:
      - master
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker compose app
        run: docker compose up --build -d